#!/bin/sh
### BEGIN INIT INFO
# Provides:       mscs
# Required-Start: $remote_fs $syslog
# Required-Stop:  $remote_fs $syslog
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# chkconfig:      345 50 50
# Description:    Minecraft Server Control Script
### END INIT INFO

# This is a wrapper to msctl that imitates traditional mscs behaviour:
# uses the same default user, config file and location.

. /etc/default/mscs
USER_NAME=${USER_NAME:-minecraft}
LOCATION=${LOCATION:-"/opt/mscs"}

if [ "$USER_NAME" = "$(whoami)" ]; then
  msctl -c /etc/default/mscs -l "$LOCATION" "$@"
else
  sudo -u $USER_NAME msctl -c /etc/default/mscs -l "$LOCATION" "$@"
fi
