#!/bin/sh
### BEGIN INIT INFO
# Provides:       mscs
# Required-Start: $remote_fs $syslog
# Required-Stop:  $remote_fs $syslog
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# chkconfig:      345 50 50
# Description:    Minecraft Server Control Script
### END INIT INFO

# This is a wrapper to msctl that imitates traditional mscs behaviour:
# uses the same default user, config file and location.

# Get executable name
PROG=$(basename $0)

# Load the mscs default file if it exists.
MSCS_DEFAULTS="/etc/default/mscs"
if [ -r $MSCS_DEFAULTS ]; then
  . $MSCS_DEFAULTS
  MSCS_ARGS="-c $MSCS_DEFAULTS "
fi

# Setup the default user name.
USER_NAME=${USER_NAME:-minecraft}

# Setup the default installation location.
LOCATION=${LOCATION:-"/opt/mscs"}

# Setup the arguments to the msctl script.
MSCS_ARGS="-p $PROG -l $LOCATION $MSCS_ARGS $@"

# Run the msctl script.
if [ "$USER_NAME" = "$(whoami)" ]; then
  msctl $MSCS_ARGS
else
  sudo -u $USER_NAME msctl $MSCS_ARGS
fi
